name: "Update docs"

on:
    push:
        tags-ignore:
            - '*'
        branches-ignore:
            - main
jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set up Go
                uses: actions/setup-go@v3
                with:
                    go-version: 1.21

            -   name: Update Swagger
                run: |
                    go install github.com/swaggo/swag/cmd/swag@latest
                    swag init -g ./cmd/serve.go -o cmd/docs

            -   name: Update API.md
                uses: addnab/docker-run-action@v3
                with:
                    image: quay.io/goswagger/swagger:latest
                    options: -v ${{ github.workspace }}:/api
                    run: |
                        cd /api
                        swagger generate markdown -f cmd/docs/swagger.json --output api.md

            -   name: Update helm chart docs
                uses: addnab/docker-run-action@v3
                with:
                    image: jnorwood/helm-docs:latest
                    options: -v ${{ github.workspace }}/charts/vmware-rest-proxy:/helm-docs
                    run: helm-docs

            -   name: Add & Commit
                uses: EndBug/add-and-commit@v9.1.3
                with:
                    add: '["cmd/docs", "api.md", "charts/vmware-rest-proxy/README.md"]'
                    author_name: "DO! DevOps bot"
                    author_email: "info@dodevops.io"
                    message: "docs: Automatic docs update"
                    push: true
